# Site settings
title: Jason Quisberth's Github Pages Website
email: 61quisberth@cardinalmail.cua.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm Jason Quisberth, a software engineer from Northern Virginia. I gradated from The
  Catholic University of America with degrees in Mechanical Engineering and Computer
  Science. I work with C, C++, MATLAB, and Python professionally. Amateurly I play 
  around with various web frameworks, languages, and libraries. My interests include 
  embedded systems, computer graphics, robotics, computer vision, and web development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://61quisberth.github.io" # the base hostname & protocol for your site
twitter_username: Jaybaby00 
github_username: 61quisberth 

# Footer Info
footer_title: Jason Quisberth's Github Pages Website

# Build settings
markdown: kramdown
